# Generated by Django 3.1.6 on 2021-02-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=200)),
            ],
        ),
    ]
