# Generated by Django 3.1.6 on 2021-02-23 22:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('MajorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, primary_key=True, region='IN', serialize=False),
        ),
    ]
